app = "suziartesanatos"
primary_region = "gru"

[build]
  dockerfile = "./Dockerfile"   # ⚠️ usar Dockerfile, não image

[env]
  NODE_ENV = "production"
  NEXT_PUBLIC_BASE_URL = "https://suziartesanatos.fly.dev"
  ADMIN_USER = "susi"
  ADMIN_PASS = "artesanato123"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls","http"]
